apiVersion: batch/v1
kind: Job
metadata:
  name: postdeal-when-sync-healthy
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: postdeal
          image: alpine:3.10.2
          command:
            - "echo"
          args:
            - "sync done!"
      restartPolicy: Never
  backoffLimit: 2
